/* Hard-coded preset decklists — read-only. Add new decks to this array. */
window.PRESET_DECKS = [
  {
    id: 'preset:Briar-PEN',
    name: 'Briar-PEN',
    savedAt: '2026-05-12T00:00:00.000Z',
    preset: true,
    cardCount: 55,
    decklist: "Name: Brage\nHero: Briar\nFormat: Silver Age\n\nArena cards\n1x Beckoning Haunt\n1x Blade Beckoner Boots\n1x Blade Beckoner Helm\n1x Blade Beckoner Plating\n1x Garland of Spring\n1x Helm of Might and Magic\n1x Nullrune Boots\n1x Star Fall\n1x Swiftstrike Bracers\n\nDeck cards\n2x Arcane Polarity (red)\n2x Arcane Seeds // Life (red)\n2x Arcanic Shockwave (red)\n1x Electrify (red)\n2x Electrostatic Discharge (red)\n2x Entwine Lightning (red)\n2x Flittering Charge (red)\n1x Jack Be Nimble (red)\n2x Lightning Surge (red)\n2x Nimblism (red)\n2x Photon Rush (red)\n2x Ravenous Rabble (red)\n1x Rootbound Carapace (red)\n2x Scar for a Scar (red)\n2x Second Strike (red)\n2x Sigil of Suffering (red)\n2x Sizzle (red)\n1x Skyzyk (red)\n2x Snatch (red)\n2x Sprout Strength (red)\n2x Static Shock (red)\n2x Weave Lightning (red)\n1 Arcane Polarity (yellow)\n2x Flourish (yellow)\n1x Sigil of Voltaris (blue)\n\nMade with ❤️ at the FaBrary\nSee the full deck @ https://fabrary.net/decks/01KKVW6JK07DNVCGWXMED0KE9Z\n1 Bloodied Oval\n1 Scepter of Pain",
    sideboardGuide: [
      { id: "kayo", hero: "Kayo", rating: "favoured", goFirst: "second", note: "Keep D-React in arsenal if possible\nUse 1 blade beckoner early to not miss the value once claw attacks\nThreaten lethal as soon as possible, abuse breakpoints\nBe wary of pummel", cardsOutRaw: "1 Blade Beckoner Plating\n1 Helm of Might and Magic\n1 Nullrune Boots\n1 Swiftstrike Bracers\n2 Arcane Polarity (red)\n1 Electrify (red)\n1 Arcane Polarity (yellow)\n1 Bloodied Oval\n1 Scepter of Pain" },
      { id: "ira", hero: "Ira", rating: "favoured", goFirst: "second", note: "Be wary of razor reflex + other blue attack reactions\nKeep blocks for on-hit chain enders\nArsenal non-attack if possible\nSave equipment as long as possible to be behind in life\nJudge their hand by blocking decisions, ira hands are easy to read", cardsOutRaw: "1 Blade Beckoner Plating\n1 Helm of Might and Magic\n1 Nullrune Boots\n1 Swiftstrike Bracers\n2 Arcane Polarity (red)\n1 Rootbound Carapace (red)\n1 Arcane Polarity (yellow)\n1 Bloodied Oval\n1 Scepter of Pain" },
      { id: "kano", hero: "Kano", rating: "favoured", goFirst: "second", note: "", cardsOutRaw: "1 Beckoning Haunt\n1 Blade Beckoner Boots\n1 Blade Beckoner Helm\n1 Blade Beckoner Plating\n1 Rootbound Carapace (red)\n1 Scar for a Scar (red)\n2 Sigil of Suffering (red)\n1 Bloodied Oval\n1 Scepter of Pain" },
      { id: "iyslander", hero: "Iyslander", rating: "unfavoured", goFirst: "second", note: "", cardsOutRaw: "1 Blade Beckoner Boots\n1 Blade Beckoner Helm\n1 Blade Beckoner Plating\n1 Star Fall\n1 Swiftstrike Bracers\n1 Rootbound Carapace (red)\n1 Scar for a Scar (red)\n2 Sigil of Suffering (red)" },
      { id: "briar", hero: "Briar", rating: "favoured", goFirst: "second", note: "", cardsOutRaw: "1 Blade Beckoner Helm\n1 Garland of Spring\n1 Nullrune Boots\n1 Star Fall\n1 Swiftstrike Bracers\n2 Arcane Polarity (red)\n1 Electrify (red)\n1 Arcane Polarity (yellow)" },
      { id: "kayo-2", hero: "Valda", rating: "unfavoured", goFirst: "second", note: "", cardsOutRaw: "1 Blade Beckoner Plating\n1 Helm of Might and Magic\n1 Nullrune Boots\n1 Swiftstrike Bracers\n2 Arcane Polarity (red)\n1 Second Strike (red)\n1 Arcane Polarity (yellow)\n1 Bloodied Oval\n1 Scepter of Pain" },
      { id: "florian", hero: "Florian", rating: "favoured", goFirst: "first", note: "", cardsOutRaw: "1 Beckoning Haunt\n1 Blade Beckoner Boots\n1 Blade Beckoner Helm\n1 Blade Beckoner Plating\n1 Arcane Polarity (red)\n1 Rootbound Carapace (red)\n2 Sigil of Suffering (red)\n1 Bloodied Oval\n1 Scepter of Pain" },
      { id: "oldhim", hero: "Oldhim", rating: "auto-loss", goFirst: "first", note: "", cardsOutRaw: "1 Beckoning Haunt\n1 Blade Beckoner Plating\n1 Helm of Might and Magic\n1 Nullrune Boots\n2 Arcane Polarity (red)\n1 Rootbound Carapace (red)\n1 Arcane Polarity (yellow)\n1 Bloodied Oval\n1 Scepter of Pain" },
      { id: "dash", hero: "Dash", rating: "favoured", goFirst: "second", note: "", cardsOutRaw: "1 Blade Beckoner Helm\n1 Garland of Spring\n1 Nullrune Boots\n1 Star Fall\n1 Swiftstrike Bracers\n2 Arcane Polarity (red)\n1 Electrify (red)\n1 Arcane Polarity (yellow)" },
      { id: "fai", hero: "Fai", rating: "favoured", goFirst: "second", note: "", cardsOutRaw: "1 Garland of Spring\n1 Helm of Might and Magic\n1 Nullrune Boots\n1 Star Fall\n1 Swiftstrike Bracers\n2 Arcane Polarity (red)\n1 Electrify (red)\n1 Arcane Polarity (yellow)" },
      { id: "dorinthea", hero: "Dorinthea", rating: "favoured", goFirst: "second", note: "", cardsOutRaw: "1 Beckoning Haunt\n1 Garland of Spring\n1 Helm of Might and Magic\n1 Nullrune Boots\n2 Arcane Polarity (red)\n1 Rootbound Carapace (red)\n1 Arcane Polarity (yellow)\n1 Bloodied Oval\n1 Scepter of Pain" },
      { id: "vynnset", hero: "Vynnset", rating: "unfavoured", goFirst: "first", note: "", cardsOutRaw: "1 Blade Beckoner Boots\n1 Blade Beckoner Helm\n1 Blade Beckoner Plating\n1 Swiftstrike Bracers\n2 Electrostatic Discharge (red)\n1 Rootbound Carapace (red)\n1 Second Strike (red)\n1 Bloodied Oval\n1 Scepter of Pain" },
      { id: "enigma", hero: "Enigma", rating: "favoured", goFirst: "first", note: "", cardsOutRaw: "1 Beckoning Haunt\n1 Blade Beckoner Plating\n1 Helm of Might and Magic\n1 Nullrune Boots\n2 Arcane Polarity (red)\n1 Rootbound Carapace (red)\n1 Arcane Polarity (yellow)\n1 Bloodied Oval\n1 Scepter of Pain" },
      { id: "riptide", hero: "Riptide", rating: "unfavoured", goFirst: "first", note: "", cardsOutRaw: "1 Blade Beckoner Plating\n1 Helm of Might and Magic\n1 Nullrune Boots\n1 Swiftstrike Bracers\n2 Arcane Polarity (red)\n1 Rootbound Carapace (red)\n1 Arcane Polarity (yellow)\n1 Bloodied Oval\n1 Scepter of Pain" },
      { id: "dromai", hero: "Dromai", rating: "even", goFirst: "first", note: "", cardsOutRaw: "1 Beckoning Haunt\n1 Blade Beckoner Plating\n1 Helm of Might and Magic\n1 Nullrune Boots\n2 Arcane Polarity (red)\n1 Rootbound Carapace (red)\n1 Arcane Polarity (yellow)\n1 Bloodied Oval\n1 Scepter of Pain" },
      { id: "dash-2", hero: "Dash", rating: "favoured", goFirst: "second", note: "", cardsOutRaw: "1 Blade Beckoner Helm\n1 Garland of Spring\n1 Nullrune Boots\n1 Star Fall\n1 Swiftstrike Bracers\n2 Arcane Polarity (red)\n1 Electrify (red)\n1 Arcane Polarity (yellow)" }
    ]
  }
];
